version: '2'

services:
  minio:
    image: 'minio/minio'
    hostname: minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  image-storage-service:
    image: 'image-storage-service:1.0'
    ports:
      - '8080:8080'
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
      - MINIO_SERVER=minio:9000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - minio
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local